# Generated by Django 4.1.4 on 2023-01-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageForCharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=99, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'страницу c графиками',
                'verbose_name_plural': 'страницы с графиками',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название графика')),
                ('slug', models.SlugField(max_length=99, unique=True, verbose_name='URL')),
                ('chart', models.ImageField(upload_to='charts', verbose_name='График')),
                ('table', models.TextField(blank=True, verbose_name='Таблица')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AboutCSharpDeveloper.pageforcharts', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'график',
                'verbose_name_plural': 'графики',
            },
        ),
    ]
